/**
 * Extra tokens for matching LiveRC / Everlaps-style strings to canonical taxonomy slugs.
 * Used only for suggestion scoring, not rule resolution.
 */
export const SLUG_EXTRA_HINT_WORDS: Record<string, string[]> = {
  "off-road-1-10-buggy-2wd": ["2wd", "2wd buggy", "17.5", "stock", "open"],
  "off-road-1-10-buggy-4wd": ["4wd", "4wd buggy", "13.5", "stock", "open"],
  "off-road-1-10-sc-2wd": ["short course", "sc 2wd", "2wd sc", "13.5"],
  "off-road-1-10-sc-4wd": ["4wd sc", "4x4", "short course"],
  "off-road-1-10-stadium-truck-2wd": ["stadium", "stadium truck", "struck"],
  "off-road-1-10-truck-4wd": ["truck", "4wd truck"],
  "off-road-2wd-open-wheel": ["open wheel", "openwheel"],
  "off-road-1-8-electric-buggy": [
    "e buggy",
    "e-buggy",
    "electric buggy",
    "eco buggy",
    "expert",
    "sportsman",
  ],
  "off-road-1-8-nitro-buggy": [
    "nitro",
    "nitro buggy",
    "1/8 nitro",
    "1:8 nitro",
    "spt",
    "pro nitro",
  ],
  "off-road-1-8-electric-truggy": ["etruggy", "e truggy", "electric truggy"],
  "off-road-1-8-nitro-truggy": ["nitro truggy", "truggy"],
  "lr-1-6-buggy-2wd": ["1:6", "or6", "gas buggy"],
  "lr-1-6-buggy-4wd": ["1:6", "or6"],
  "lr-1-6-short-course": ["1:6", "gas sc"],
  "lr-1-5-brushless": ["1:5", "large scale"],
  "on-road-lg-super-touring": ["1/5", "super touring", "touring"],
  "on-road-lg-rally": ["1/5", "rally"],
  "on-road-1-10-nitro-sedan": ["nitro sedan", "sedan", "200mm"],
  "on-road-1-8-electric": ["1/8 electric", "on road electric"],
  "on-road-1-8-nitro": ["1/8 nitro", "on road nitro"],
  "on-road-istc-touring": ["touring", "istc", "21.5", "17.5", "mod touring", "roar"],
  "on-road-gt12": ["gt12", "gt-12"],
  "on-road-1-12-pan-car": ["1/12", "1:12", "13.5", "pan car"],
  "on-road-formula-1": ["f1", "25.5", "formula"],
  "on-road-usgt": ["usgt", "21.5"],
  "on-road-vta": ["vta", "vintage"],
  "on-road-tamiya-tt-02": ["tt02", "tt-02", "tamiya"],
  "oval-sprint": ["sprint", "sprint car", "losi sprint", "360"],
  "oval-stock-car": ["stock car", "street stock", "mudboss", "nascar"],
  "rock-crawler": ["crawler", "trail"],
}
